export const defaultApprovedFoods = [
  "Chicken breast",
  "Turkey mince",
  "Greek yogurt",
  "Eggs",
  "Tuna or salmon",
  "Tofu or tempeh",
  "Rice",
  "Oats",
  "Potatoes",
  "Wholegrain wraps",
  "Fruit",
  "Broccoli",
  "Mixed salad",
  "Mixed vegetables",
  "Peppers",
  "Berries",
  "Olive oil",
  "Avocado",
  "Peanut butter",
  "Light mayo",
];
